name: smart_clinic_app
description: Smart Clinic
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3

  # Navigation
  go_router: ^14.6.2

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.3
  animate_do: ^3.3.4
  fl_chart: ^0.69.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image_picker: ^1.1.2

  # Utils
  get_it: ^8.0.3
  injectable: ^2.5.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
